# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v3
    - name: Install Erlang
      run: asdf plugin-add erlang \ asdf install erlang 27.1.3 \ asdf global erlang 27.1.3
    - name: Install Elixir
      run: asdf plugin-add elixir \ asdf install elixir 1.17.3-otp-27 \ asdf global elixir 1.17.3-otp-27
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
